name: Linting
on:
  push:
    branches:
    - main
  pull_request:

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Ruff
        uses: astral-sh/ruff-action@v3